#!/bin/bash

exec 6<>/dev/tcp/127.0.0.1/3001 && echo "server already running on port 3001, exit ..." && exit 1
exec 6>&-
exec 6<&-
NODE_ENV=test node ./script/clean_db.js
NODE_ENV=test node ./app.js &
sleep 1
casperjs test test/integration/*
kill -9 $!
